@startuml
title Flux recherche et historique des recherches (Frontend)
autonumber

actor "Utilisateur" as User
participant "UI" as UI
participant "Backend" as BE
database "Base de données" as DB

== Connexion utilisateur ==
User -> UI : Saisie nom utilisateur + mot de passe
User -> UI : Clique sur "Login"

UI -> BE : authUser(user_cred)
BE -> DB : authUser(user_cred)
DB --> BE : user_data
BE --> UI : JWT

UI --> UI : enregistre JWT dans localStorage
UI --> User : redirige /fetch

== Déconnexion utilisateur ==
User -> UI : Clique sur la bouton "Sign out"

UI --> UI : supprime JWT du localStorage

@enduml