@startuml
title Flux recherche et historique des recherches (Frontend)
autonumber

actor "Utilisateur" as User
participant "UI" as UI
participant "Backend" as BE
database "Base de données" as DB

== Création de recherche personnalisée ==
User -> UI : Saisie des filtres
User -> UI : Ajout d'un titre pour la recherche personnalisée
User -> UI : Appuie sur le bouton "Fetch News"

UI -> BE : saveCustomSearch(custom_search)
BE -> DB : saveCustomSearch(selectedArticles)
DB --> BE : confirmation_sauvegarde

== Récupération de recherche personnalisée ==
User -> UI : Login par l'utilisateur
UI -> BE : GET /customsearch(user_id)
BE -> DB : getUserCustomSearch(user_id)
DB --> BE : custom_search_result
BE --> UI : custom_search_result
User -> UI : Sélectionne sa recherche personnalisée

UI --> UI : Mise à jour des filtres

@enduml