@startuml

title Class Diagram - Backend

'left to right direction

package "Presentation Layer" {
    class router
    class newsRouter
    class newsController
}

package "Business Layer" {
    class newsService
    class linkFinder
    class scraper
}

package "Infrastructure Layer" {
    class "Input/Output" as io
    class BasicCrawler
    class CheerioCrawler
}

EndUser --> router
router --> newsRouter
newsRouter --> newsController
newsController --> newsService
newsService --> linkFinder
linkFinder --> io
io --> linkFinder
linkFinder --> scraper
scraper --> BasicCrawler
BasicCrawler --> scraper
scraper --> CheerioCrawler
CheerioCrawler --> scraper

@enduml